In [19]:
import pandas as pd

In [26]:
data = {
    'Experiment': ['Exp-1', 'Exp-1', 'Exp-2', 'Exp-2','Exp-3', 'Exp-3','Exp-4', 'Exp-4'],
    'Variant': ['Ctrl', 'A', 'Ctrl', 'A + B', 'Ctrl', 'C', 'Ctrl', 'B + C'],
    'Users': [15328, 15503, 17324, 17102, 22319, 21981, 18248, 18432],
    'Converted Users': [786, 730, 871, 873, 1141, 1230, 916, 993]
}

experiment_data = pd.DataFrame(data)

experiment_data['Conversion Rate'] = experiment_data['Converted Users'] / experiment_data['Users']

decision_results = pd.DataFrame()

for experiment in set(data['Experiment']):
    control_value = experiment_data.loc[(experiment_data['Experiment'] == experiment) & (experiment_data['Variant'] == 'Ctrl')]['Conversion Rate'].values[0]
    temp = experiment_data.loc[(experiment_data['Experiment'] == experiment)]
    temp['Growth/Decline'] = (experiment_data['Conversion Rate'] - control_value) / control_value
    decision_results = pd.concat([decision_results, temp], ignore_index=True)

/var/folders/tt/_tq7thkd6hx_grhd7r9xdfr40000gn/T/ipykernel_25946/3243401716.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['Growth/Decline'] = (experiment_data['Conversion Rate'] - control_value) / control_value
/var/folders/tt/_tq7thkd6hx_grhd7r9xdfr40000gn/T/ipykernel_25946/3243401716.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['Growth/Decline'] = (experiment_data['Conversion Rate'] - control_value) / control_value
/var/folders/tt/_tq7thkd6hx_grhd7r9xdfr40000gn/T/ipykernel_25946/3243401716.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['Growth/Decline'] = (experiment_data['Conversion Rate'] - control_value) / control_value
/var/folders/tt/_tq7thkd6hx_grhd7r9xdfr40000gn/T/ipykernel_25946/3243401716.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['Growth/Decline'] = (experiment_data['Conversion Rate'] - control_value) / control_value

In [21]:
decision_results

  Experiment Variant  Users  Converted Users  Conversion Rate  Growth/Decline
0      Exp-2    Ctrl  17324              871         0.050277        0.000000
1      Exp-2   A + B  17102              873         0.051047        0.015307
2      Exp-4    Ctrl  18248              916         0.050197        0.000000
3      Exp-4   B + C  18432              993         0.053874        0.073239
4      Exp-1    Ctrl  15328              786         0.051279        0.000000
5      Exp-1       A  15503              730         0.047088       -0.081731
6      Exp-3    Ctrl  22319             1141         0.051122        0.000000
7      Exp-3       C  21981             1230         0.055957        0.094578

In [23]:
decision_results[decision_results['Variant'] != 'Ctrl'].sort_values(by = 'Growth/Decline', ascending = False)

  Experiment Variant  Users  Converted Users  Conversion Rate  Growth/Decline
7      Exp-3       C  21981             1230         0.055957        0.094578
3      Exp-4   B + C  18432              993         0.053874        0.073239
1      Exp-2   A + B  17102              873         0.051047        0.015307
5      Exp-1       A  15503              730         0.047088       -0.081731